### PR TITLE
The "smoother movement?" merge

### PR DESCRIPTION
**Pull request by IntOverflow-maxwell**
Not sure if this code is up to standard, but oh well.

### CODE REVIEW

**Comment by Meigyoku-Thmn** [comment]
@IntOverflow-maxwell Can you change this PR to merge into the [development](https://github.com/Meigyoku-Thmn/ThMouseX/tree/development) branch?

**Comment by Meigyoku-Thmn** [comment]
@IntOverflow-maxwell Wow, it's almost perfect. Thank you so much.

**Comment by Meigyoku-Thmn** [comment]
@IntOverflow-maxwell Can you explain the condition `xDist + yDist > 10`, what is its' effect?

**Comment by IntOverflow-maxwell** [comment]
xDist + yDist > 10 is mainly because getting the player's movement velocity and judging if the mouse is longer than 1 frame of movement might be unreliable before a few frames have happened, so it's good to fall back to forced movement when velocity judgements aren't on point and the distance between the player and the mouse is long. (Basically, you REALLY want to move, I'll move.) As soon as the player starts moving, it should be running correctly, and the statement is basically useless. 10 is chosen because 10 pixels per frame is much, much faster than normal shoot em' up / bullet hell movement speeds. I don't know of a better solution, so this hacky one is what I chose.

**Pull request merged**
